
import makeupOne from './cos-img/product-img/products/makeup/blusher/blush (5).jpg';
import makeupTwo from './cos-img/product-img/products/makeup/bridal-makeup/makeup (6).jpg';
import makeupThree from './cos-img/product-img/products/makeup/blusher/blush (28).jpg';
import makeupFour from './cos-img/product-img/products/makeup/blusher/blush (35).jpg';

import hairOne from './cos-img/product-img/products/shampoo/garnier/hair (37).jpg';
import hairTwo from './cos-img/product-img/products/shampoo/provost/hair (1).jpg';
import hairThree from './cos-img/product-img/products/shampoo/loreal/hair (25).jpg';
import hairFour from './cos-img/product-img/products/shampoo/loreal/hair (31).jpg';
import hairFive from './cos-img/product-img/products/shampoo/TRESemme/hair (1).jpg';
import hairSix from './cos-img/product-img/products/shampoo/loreal/hair (3).jpg';
import hairSeven from './cos-img/product-img/products/shampoo/loreal/hair (19).jpg';
import hairEight from './cos-img/product-img/products/shampoo/loreal/hair (20).jpg';
import hairNine from './cos-img/product-img/products/shampoo/loreal/hair (21).jpg';
import hairTen from './cos-img/product-img/products/shampoo/loreal/hair (24).jpg';
import hair11 from './cos-img/product-img/products/shampoo/loreal/hair (26).jpg';
import hair12 from './cos-img/product-img/products/shampoo/loreal/hair (27).jpg';
import hair13 from './cos-img/product-img/products/shampoo/loreal/hair (32).jpg';
import hair14 from './cos-img/product-img/products/shampoo/loreal/hair (33).jpg';
import hair15 from './cos-img/product-img/products/shampoo/loreal/hair (34).jpg';
import hair16 from './cos-img/product-img/products/shampoo/loreal/hair (35).jpg';
import hair17 from './cos-img/product-img/products/shampoo/loreal/hair (39).jpg';
import hair18 from './cos-img/product-img/products/shampoo/loreal/hair (43).jpg';
import hair19 from './cos-img/product-img/products/shampoo/loreal/hair (44).jpg';
import hair20 from './cos-img/product-img/products/shampoo/loreal/hair (54).jpg';
import hair21 from './cos-img/product-img/products/shampoo/loreal/hair (53).jpg';
import hair22 from './cos-img/product-img/products/shampoo/loreal/hair (55).jpg';
import hair23 from './cos-img/product-img/products/shampoo/loreal/hair (56).jpg';
import hair24 from './cos-img/product-img/products/shampoo/loreal/hair (57).jpg';
import hair25 from './cos-img/product-img/products/shampoo/loreal/hair (58).jpg';
import hair26 from './cos-img/product-img/products/shampoo/loreal/hair (59).jpg';
import hair27 from './cos-img/product-img/products/shampoo/loreal/hair (60).jpg';
import hair28 from './cos-img/product-img/products/shampoo/loreal/hair (61).jpg';
import hair29 from './cos-img/product-img/products/shampoo/loreal/hair (62).jpg';
import hair30 from './cos-img/product-img/products/shampoo/loreal/hair (63).jpg';
import hair31 from './cos-img/product-img/products/shampoo/loreal/hair (64).jpg';
import hair32 from './cos-img/product-img/products/shampoo/loreal/hair (65).jpg';
import hair33 from './cos-img/product-img/products/shampoo/loreal/hair (66).jpg';
import hair34 from './cos-img/product-img/products/shampoo/garnier/hair (1).jpg';
import hair35 from './cos-img/product-img/products/shampoo/garnier/hair (2).jpg';
import hair36 from './cos-img/product-img/products/shampoo/garnier/hair (3).jpg';
import hair37 from './cos-img/product-img/products/shampoo/garnier/hair (4).jpg';
import hair38 from './cos-img/product-img/products/shampoo/garnier/hair (5).jpg';
import hair39 from './cos-img/product-img/products/shampoo/garnier/hair (6).jpg';
import hair40 from './cos-img/product-img/products/shampoo/garnier/hair (7).jpg';
import hair41 from './cos-img/product-img/products/shampoo/garnier/hair (8).jpg';
import hair42 from './cos-img/product-img/products/shampoo/garnier/hair (9).jpg';
import hair43 from './cos-img/product-img/products/shampoo/garnier/hair (10).jpg';
import hair44 from './cos-img/product-img/products/shampoo/garnier/hair (11).jpg';
import hair45 from './cos-img/product-img/products/shampoo/garnier/hair (12).jpg';
import hair46 from './cos-img/product-img/products/shampoo/garnier/hair (13).jpg';
import hair47 from './cos-img/product-img/products/shampoo/garnier/hair (14).jpg';
import hair48 from './cos-img/product-img/products/shampoo/garnier/hair (15).jpg';
import hair49 from './cos-img/product-img/products/shampoo/garnier/hair (16).jpg';
import hair50 from './cos-img/product-img/products/shampoo/garnier/hair (17).jpg';
import hair51 from './cos-img/product-img/products/shampoo/garnier/hair (18).jpg';
import hair52 from './cos-img/product-img/products/shampoo/garnier/hair (19).jpg';
import hair53 from './cos-img/product-img/products/shampoo/garnier/hair (20).jpg';
import hair54 from './cos-img/product-img/products/shampoo/garnier/hair (21).jpg';
import hair55 from './cos-img/product-img/products/shampoo/garnier/hair (22).jpg';
import hair56 from './cos-img/product-img/products/shampoo/garnier/hair (23).jpg';
import hair57 from './cos-img/product-img/products/shampoo/garnier/hair (24).jpg';
import hair58 from './cos-img/product-img/products/shampoo/garnier/hair (25).jpg';
import hair59 from './cos-img/product-img/products/shampoo/garnier/hair (26).jpg';
import hair60 from './cos-img/product-img/products/shampoo/garnier/hair (27).jpg';
import hair61 from './cos-img/product-img/products/shampoo/garnier/hair (28).jpg';
import hair62 from './cos-img/product-img/products/shampoo/garnier/hair (29).jpg';
import hair63 from './cos-img/product-img/products/shampoo/garnier/hair (30).jpg';
import hair64 from './cos-img/product-img/products/shampoo/garnier/hair (31).jpg';
import hair65 from './cos-img/product-img/products/shampoo/garnier/hair (32).jpg';
import hair66 from './cos-img/product-img/products/shampoo/garnier/hair (33).jpg';
import hair67 from './cos-img/product-img/products/shampoo/garnier/hair (34).jpg';
import hair68 from './cos-img/product-img/products/shampoo/garnier/hair (35).jpg';
import hair69 from './cos-img/product-img/products/shampoo/garnier/hair (36).jpg';


import bodyOne from './cos-img/product-img/products/body/enchanteur/body (1).jpg';
import bodyTwo from './cos-img/product-img/products/body/enchanteur/body (2).jpg';
import bodyThree from './cos-img/product-img/products/body/enchanteur/body (3).jpg';
import bodyFour from './cos-img/product-img/products/body/enchanteur/body (4).jpg';
import bodyFive from './cos-img/product-img/products/body/enchanteur/body (5).jpg';
import bodySix from './cos-img/product-img/products/body/enchanteur/body (6).jpg';
import bodySeven from './cos-img/product-img/products/body/enchanteur/body (7).jpg';
import bodyEight from './cos-img/product-img/products/body/enchanteur/body (8).jpg';
import bodyNine from './cos-img/product-img/products/body/enchanteur/body (9).jpg';
import bodyTen from './cos-img/product-img/products/body/enchanteur/body (10).jpg';
import body11 from './cos-img/product-img/products/body/enchanteur/body (11).jpg';
import body12 from './cos-img/product-img/products/body/enchanteur/body (12).jpg';
import body13 from './cos-img/product-img/products/body/enchanteur/body (13).jpg';
import body14 from './cos-img/product-img/products/body/enchanteur/body (14).jpg';
import body15 from './cos-img/product-img/products/body/enchanteur/body (15).jpg';
import body16 from './cos-img/product-img/products/body/enchanteur/body (16).jpg';
import body17 from './cos-img/product-img/products/body/enchanteur/body (17).jpg';
import body18 from './cos-img/product-img/products/body/enchanteur/body (18).jpg';
import body19 from './cos-img/product-img/products/body/enchanteur/body (19).jpg';
import body20 from './cos-img/product-img/products/body/enchanteur/body (20).jpg';
import body21 from './cos-img/product-img/products/body/enchanteur/body (21).jpg';
import body22 from './cos-img/product-img/products/body/enchanteur/body (22).jpg';
import body23 from './cos-img/product-img/products/body/enchanteur/body (23).jpg';
import body24 from './cos-img/product-img/products/body/enchanteur/body (24).jpg';
import body25 from './cos-img/product-img/products/body/enchanteur/body (25).jpg';



 
import lipOne from './cos-img/product-img/products/makeup/lipStick/lips (7).jpg';


import faceCremeOne from './cos-img/product-img/products/faceCreme/face-creme/creme (2).jpg';
import sunCremeOne from './cos-img/product-img/products/faceCreme/sun-creme/sunCreme (1).jpg';
import sunCremeTwo from './cos-img/product-img/products/faceCreme/sun-creme/sunCreme (2).jpg';
import sunCremeThree from './cos-img/product-img/products/faceCreme/sun-creme/sunCreme (3).jpg';
import sunCremeFour from './cos-img/product-img/products/faceCreme/sun-creme/sunCreme (4).jpg';
import sunCremeFive from './cos-img/product-img/products/faceCreme/sun-creme/sunCreme (5).jpg';
import sunCremeSix from './cos-img/product-img/products/faceCreme/sun-creme/sunCreme (6).jpg';
import sunCremeSeven from './cos-img/product-img/products/faceCreme/sun-creme/sunCreme (7).jpg';
import sunCremeEight from './cos-img/product-img/products/faceCreme/sun-creme/sunCreme (8).jpg';


export const productsList = [
    {
        id: 1,
        period: "new",
        img: faceCremeOne,
        type: "Night creme",
        class: "face creme",
        link: "creme",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "L'OREAL Nutrition Intense, Age perfect cell renewal for everyday use",
        size: "85ml",
        price: 12.75,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 2,
        period: "try me",
        img: makeupOne,
        type: "Sephora Blusher",
        class: "blusher",
        link: "makeup",
        brand: "sephora",
        target:"woman",
        rank: "new",
        description: "Whether you choose rose or peachy, blush up your cheeks with Sephora",
        size: "30ml",
        price: 6.30,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 3,
        period: "new",
        img: sunCremeSix,
        type: "sun creme",
        class: "face creme",
        link: "creme",
        brand: "Diasaar",
        target:"woman",
        rank: "new",
        description: "Diasaar sun creme for ultimate protection from the uva and uvb sun light",
        size: "95ml/ 135ml",
        price: 10.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 4,
        period: "grab me",
        img: hairOne,
        type: "Garnier shampo",
        class: "shampoo",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "ulraDoux shampo avocado oil, argan oil & hony, green tea, flower cotton",
        size: "250ml/ 400ml",
        price: 7.80,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 5,
        period: "try me",
        img: makeupTwo,
        type: "Hd staurated colors",
        class: "bridal makeUp",
        link: "makeup",
        brand: "everbeuty",
        target:"woman",
        rank: "new",
        description: "3 hot designs and a makeup kit. Comes with a variety of shades",
        size: "15 saturated color",
        price: 18.05,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 6,
        period: "new",
        img: makeupThree,
        type: "Dior Blusher",
        class: "blusher",
        link: "makeup",
        brand: "dior",
        target:"woman",
        rank: "new",
        description: "blush from Dior that gives cheeks intense, ultra-pigmented color that lasts",
        size: "30g / pink/ red/ peach",
        price: 9.15,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 7,
        period: "try me",
        img: makeupFour,
        type: "Fit me Blusher",
        class: "blusher",
        link: "makeup",
        brand: "fitme",
        target:"woman",
        rank: "new",
        description: "FIT me blush the second colloction of nude colors from FITme",
        size: "20g / ivory / light beige",
        price: 7.60,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 8,
        period: "new",
        img: lipOne ,
        type: "Doll Lipstick ",
        class: "lipstick",
        link: "makeup",
        brand: "doll",
        target:"woman",
        rank: "new",
        description: "the Doll Beauty lipsticks are versatile, highly pigmented and lightweight",
        size: "7g/ 12 color",
        price: 8.80,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 9,
        period: "take me",
        img: hairThree,
        type: "shampo & oil repleacement",
        class: "collection",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the new collection from elseve for tinted, or bleached and dry hair with keratin",
        size: "300ml/ 110ml",
        price: 21.90,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 10,
        period: "try me",
        img: hairFour,
        type: "shampo & condtioner",
        class: "collection",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "Elseve for tinted hair and coloration for long lasting and shining color",
        size: "350ml / 300ml",
        price: 15.40,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 11,
        period: "new",
        img: hairFive,
        type: "TRESemme shampo & hairMask",
        class: "collection",
        link: "hair",
        brand: "tresemme",
        target:"woman",
        rank: "new",
        description: "the ultra shine shampo and hairCreme for dry, damaged and colored hair",
        size: "480ml/ 200ml",
        price: 11.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 12,
        period: "take me",
        img: hairTwo,
        type: "Shampo & oil repleacement",
        class: "shampoo",
        link: "hair",
        brand: "provost",
        target:"woman",
        rank: "new",
        description: "PROvost shampo condtioner and serum for frizzy, dry and lost colored hair",
        size: "750ml/ 7500ml/ 300ml",
        price: 9.80 ,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 13,
        period: "try me",
        img: sunCremeOne,
        type: "sun creme",
        class: "face creme",
        link: "creme",
        brand: "Eucerin",
        target:"woman",
        rank: "new",
        description: "Eucerin the new sunCreme for senstive skin to chellange the sun",
        size: "110ml/50+&90-SPF",
        price: 8.90,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 14,
        period: "new",
        img: sunCremeTwo,
        type: "sun creme",
        class: "face creme",
        link: "creme",
        brand: "Dermagor",
        target:"woman",
        rank: "new",
        description: "the for greasy and all skine type Dermagor sunCreme for vibrating summer",
        size: "110ml/50+&90-SPF",
        price: 10.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 15,
        period: "new",
        img: sunCremeThree,
        type: "sun creme",
        class: "face creme",
        link: "creme",
        brand: "Bonjour",
        target:"woman",
        rank: "new",
        description: "Bonjour for every hot morning to be the last one standing",
        size: "90ml/ 60&90SPF",
        price: 4.75,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 16,
        period: "try me",
        img: sunCremeFour,
        type: "sun creme",
        class: "face creme",
        link: "creme",
        brand: "Clarins",
        target:"woman",
        rank: "new",
        description: "the ultimate protection from the sun with our new sunCreme for long exposure",
        size: "105ml/ 60&90SPF",
        price: 14.05,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 17,
        period: "take me",
        img: sunCremeFive,
        type: "sun creme",
        class: "face creme",
        link: "creme",
        brand: "Leopard",
        target:"woman",
        rank: "new",
        description: "leopard sunCreme for long lasting sun protection and hydration",
        size: "90ml/ 40&50+SPF",
        price: 7.25,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 18,
        period: "new",
        img: sunCremeSeven,
        type: "sun creme",
        class: "face creme",
        link: "creme",
        brand: "Attitude",
        target:"kids",
        rank: "new",
        description: "the soft and protective sunCreme for your little angle",
        size: "75ml/ 60&50+&SPF",
        price: 6.95,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 19,
        period: "try me",
        img: sunCremeEight,
        type: "sun creme",
        class: "face creme",
        link: "creme",
        brand: "Attitude",
        target:"woman",
        rank: "new",
        description: "the soft and protective sunCreme with our new Alovera formula",
        size: "95ml/ 60&90&SPF",
        price: 9.15,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 20,
        period: "new",
        img: hairSix,
        type: "Elseve gold collection",
        class: "collection",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "best-seller",
        description: "the ever eveloving gold hair collection from loreal paris",
        size: "380ml/200ml/150ml",
        price: 32.75,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 21,
        period: "new",
        img: hairSeven,
        type: "Elseve shampo",
        class: "shampoo",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the ultra shine shampo for long and dry, damaged and brittle hair",
        size: "380ml",
        price: 7.80,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 22,
        period: "try me",
        img: hairEight,
        type: "Elseve conditioner",
        class: "conditioner",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the ultra shine conditioner hairCreme for dry, damaged and colored hair",
        size: "380ml",
        price: 5.95,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 23,
        period: "take me",
        img: hairNine,
        type: "Elseve shampo",
        class: "shampoo",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "elseve hair shampo for dry, ,lost color and long brittle hair",
        size: "380ml",
        price: 6.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 24,
        period: "take me",
        img: hairTen,
        type: "Elsve shampo",
        class: "shampoo",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 7.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 25,
        period: "take me",
        img: hair11,
        type: "Elsve shampo",
        class: "conditioner",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 6.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 26,
        period: "take me",
        img: hair12,
        type: "Elsve shampo",
        class: "conditioner",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 8.70,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 27,
        period: "take me",
        img: hair13,
        type: "Elsve shampo",
        class: "shampoo",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 9.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 28,
        period: "try me",
        img: hair14,
        type: "Elsve shampo",
        class: "shampoo",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 9.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 29,
        period: "try me",
        img: hair15,
        type: "Elsve shampo",
        class: "shampoo",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 9.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 30,
        period: "try me",
        img: hair16,
        type: "Elsve shampo",
        class: "shampoo",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 11.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 31,
        period: "try me",
        img: hair17,
        type: "Elsve shampo",
        class: "shampoo",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 9.25,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 32,
        period: "try me",
        img: hair18,
        type: "Elsve shampo",
        class: "collection",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 19.60,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 33,
        period: "try me",
        img: hair19,
        type: "Elsve shampo",
        class: "collection",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 10.00,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 34,
        period: "try me",
        img: hair20,
        type: "Elsve shampo",
        class: "shampoo",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 7.10,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 35,
        period: "try me",
        img: hair21,
        type: "Elsve shampo",
        class: "shampoo",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "best seller",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 9.60,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 36,
        period: "try me",
        img: hair22,
        type: "Elsve mask",
        class: "hair mask",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "best seller",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 13.60,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 37,
        period: "try me",
        img: hair23,
        type: "Elsve mask",
        class: "shampoo",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 16.20,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 38,
        period: "try me",
        img: hair24,
        type: "Elsve shampo",
        class: "hair mask",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "best seller",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 12.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 39,
        period: "try me",
        img: hair25,
        type: "Elsve shampo",
        class: "hair mask",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "best seller",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 12.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 40,
        period: "try me",
        img: hair26,
        type: "Elsve shampo",
        class: "collection",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 11.80,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 41,
        period: "try me",
        img: hair27,
        type: "Elsve shampo",
        class: "hair mask",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "best seller",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 10.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 42,
        period: "try me",
        img: hair28,
        type: "Elsve shampo",
        class: "collection",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "best seller",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 35.80,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 43,
        period: "try me",
        img: hair29,
        type: "Elsve shampo",
        class: "collection",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 38.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 44,
        period: "try me",
        img: hair30,
        type: "Elsve shampo",
        class: "conditioner",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 8.10,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 45,
        period: "try me",
        img: hair31,
        type: "Elsve shampo",
        class: "conditioner",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 7.80,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 46,
        period: "try me",
        img: hair32,
        type: "Elsve shampo",
        class: "conditioner",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 7.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 47,
        period: "try me",
        img: hair33,
        type: "Elsve shampo",
        class: "conditioner",
        link: "hair",
        brand: "loreal",
        target:"woman",
        rank: "new",
        description: "the old school shampo from elesve for greasy and oily hair",
        size: "380ml",
        price: 8.10,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 48,
        period: "try me",
        img: hair34,
        type: "Garnier shampo",
        class: "shampoo",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "best seller",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 7.60,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 49,
        period: "try me",
        img: hair35,
        type: "Garnier shampo",
        class: "shampoo",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 7.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 50,
        period: "try me",
        img: hair36,
        type: "Garnier shampo",
        class: "shampoo",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 6.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 51,
        period: "try me",
        img: hair37,
        type: "Garnier shampo",
        class: "shampoo",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 8.10,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 52,
        period: "try me",
        img: hair38,
        type: "Garnier shampo",
        class: "shampoo",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 7.20,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 53,
        period: "try me",
        img: hair39,
        type: "Garnier shampo",
        class: "shampoo",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "best seller",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 6.80,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 54,
        period: "try me",
        img: hair40,
        type: "Garnier shampo",
        class: "shampoo",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 8.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 55,
        period: "try me",
        img: hair41,
        type: "Garnier shampo conditioner",
        class: "collection",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 12.25,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 56,
        period: "try me",
        img: hair42,
        type: "Garnier shampo",
        class: "shampoo",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 7.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 57,
        period: "try me",
        img: hair43,
        type: "Garnier shampo",
        class: "shampoo",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 7.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 58,
        period: "try me",
        img: hair44,
        type: "Garnier shampo",
        class: "shampoo",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 7.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 59,
        period: "try me",
        img: hair45,
        type: "Garnier shampo",
        class: "shampoo",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 7.20,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 60,
        period: "try me",
        img: hair46,
        type: "Garnier conditioner",
        class: "conditioner",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "best seller",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 8.20,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 61,
        period: "try me",
        img: hair47,
        type: "Garnier conditioner",
        class: "conditioner",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 7.30,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 62,
        period: "try me",
        img: hair48,
        type: "Garnier conditioner",
        class: "conditioner",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 9.00,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 63,
        period: "try me",
        img: hair49,
        type: "Garnier conditioner",
        class: "conditioner",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 6.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 64,
        period: "try me",
        img: hair50,
        type: "Garnier hair mask",
        class: "hair mask",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 6.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 65,
        period: "try me",
        img: hair51,
        type: "Garnier hair mask",
        class: "hair mask",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 6.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 66,
        period: "try me",
        img: hair52,
        type: "Garnier hair mask",
        class: "hair mask",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 6.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 67,
        period: "try me",
        img: hair53,
        type: "Garnier conditioner",
        class: "conditioner",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 6.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 68,
        period: "try me",
        img: hair54,
        type: "Garnier conditioner",
        class: "conditioner",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 6.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 69,
        period: "try me",
        img: hair55,
        type: "Garnier conditioner",
        class: "conditioner",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 7.25,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 70,
        period: "try me",
        img: hair56,
        type: "Garnier conditioner",
        class: "conditioner",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 7.05,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 71,
        period: "try me",
        img: hair57,
        type: "Garnier conditioner",
        class: "conditioner",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 8.00,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 72,
        period: "try me",
        img: hair58,
        type: "Garnier conditioner",
        class: "conditioner",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 7.30,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 73,
        period: "try me",
        img: hair59,
        type: "Garnier conditioner",
        class: "conditioner",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 8.10,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 74,
        period: "try me",
        img: hair60,
        type: "Garnier shampo",
        class: "shampoo",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 7.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 75,
        period: "try me",
        img: hair61,
        type: "shampo conditioner&creme",
        class: "collection",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 16.10,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 76,
        period: "try me",
        img: hair62,
        type: "Garnier shampo",
        class: "collection",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 9.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 77,
        period: "try me",
        img: hair63,
        type: "Garnier super Package",
        class: "collection",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 28.75,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 78,
        period: "try me",
        img: hair64,
        type: "Garnier hair mask",
        class: "hair mask",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 9.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 79,
        period: "try me",
        img: hair65,
        type: "Garnier hair mask",
        class: "hair mask",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 10.60,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 80,
        period: "try me",
        img: hair66,
        type: "Garnier hair mask",
        class: "hair mask",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "new",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 11.05,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 81,
        period: "try me",
        img: hair67,
        type: "Garnier hair mask",
        class: "hair mask",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 9.80,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 82,
        period: "try me",
        img: hair68,
        type: "Garnier hair mask",
        class: "hair mask",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "best seller",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 9.80,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 83,
        period: "try me",
        img: hair69,
        type: "Garnier shampo",
        class: "shampoo",
        link: "hair",
        brand: "garnier",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all hair types, dry and damaged from garnier",
        size: "300ml",
        price: 9.75,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 84,
        period: "try me",
        img: bodyOne,
        type: "enchanteur Talc",
        class: "OTHERS",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "180ml",
        price: 7.25,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 85,
        period: "try me",
        img: bodyTwo,
        type: "enchanteur shower gel",
        class: "showerGel",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "380ml",
        price: 13.75,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 86,
        period: "try me",
        img: bodyThree,
        type: "shower gel & lotion",
        class: "bodyLotion",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "350ml/380ml",
        price: 24.15,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 87,
        period: "try me",
        img: bodyFour,
        type: "enchanteur Talc",
        class: "OTHERS",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "300ml",
        price: 12.30,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 88,
        period: "try me",
        img: bodyFive,
        type: "enchanteur Talc",
        class: "OTHERS",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "180ml",
        price: 7.30,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 89,
        period: "try me",
        img: bodySix,
        type: "enchanteur Talc",
        class: "OTHERS",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "300ml",
        price: 12.30,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 90,
        period: "try me",
        img: bodySeven,
        type: "enchanteur Talc",
        class: "OTHERS",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "200ml",
        price: 8.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 91,
        period: "try me",
        img: bodyEight,
        type: "enchanteur Lotion",
        class: "bodyLotion",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "300ml",
        price: 14.25,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 92,
        period: "try me",
        img: bodyNine,
        type: "enchanteur Lotion",
        class: "bodyLotion",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "360ml",
        price: 15.10,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 93,
        period: "try me",
        img: bodyTen,
        type: "enchanteur Lotion",
        class: "bodyLotion",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "300ml",
        price: 13.30,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 94,
        period: "try me",
        img: body11,
        type: "enchanteur Lotion",
        class: "bodyLotion",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "360ml",
        price: 16.60,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 95,
        period: "try me",
        img: body12,
        type: "enchanteur Lotion",
        class: "bodyLotion",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "360ml",
        price: 15.80,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 96,
        period: "try me",
        img: body13,
        type: "enchanteur Lotion",
        class: "bodyLotion",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "300ml",
        price: 13.25,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 97,
        period: "try me",
        img: body14,
        type: "enchanteur Lotion",
        class: "bodyLotion",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "300ml",
        price: 13.25,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 98,
        period: "try me",
        img: body15,
        type: "enchanteur Lotion",
        class: "bodyLotion",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "360ml",
        price: 14.60,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 99,
        period: "try me",
        img: body16,
        type: "enchanteur Lotion",
        class: "bodyLotion",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "300ml",
        price: 12.80,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 100,
        period: "try me",
        img: body17,
        type: "enchanteur Lotion",
        class: "OTHERS",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "300ml",
        price: 12.25,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 101,
        period: "try me",
        img: body18,
        type: "enchanteur Lotion",
        class: "OTHERS",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "200ml",
        price: 8.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 102,
        period: "try me",
        img: body19,
        type: "enchanteur Lotion",
        class: "OTHERS",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "300ml",
        price: 12.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 103,
        period: "try me",
        img: body20,
        type: "enchanteur showerGel",
        class: "showerGel",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "300ml",
        price: 13.20,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 104,
        period: "try me",
        img: body21,
        type: "enchanteur showerGel",
        class: "showerGel",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "330ml",
        price: 13.80,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 105,
        period: "try me",
        img: body22,
        type: "enchanteur showerGel",
        class: "showerGel",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "330ml",
        price: 13.50,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 106,
        period: "try me",
        img: body23,
        type: "enchanteur showerGel",
        class: "showerGel",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "300ml",
        price: 12.90,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 107,
        period: "try me",
        img: body24,
        type: "enchanteur showerGel",
        class: "showerGel",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "400ml",
        price: 16.40,
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 108,
        period: "try me",
        img: body25,
        type: "enchanteur showerGel",
        class: "showerGel",
        link: "body",
        brand: "enchanteur",
        target:"woman",
        rank: "popular",
        description: "the ultimate repair for all skin types, dry and damaged from enchanteur",
        size: "550ml",
        price: 18.70,
        inCart: false,
        count: 0,
        total: 0
    },
];







export const detailsProduct = {
    id: 1,
    period: "new",
    img: faceCremeOne,
    type: "Night creme",
    description: "L'OREAL Nutrition Intense, Age perfect cell renewal for everyday use",
    size: "85ml",
    price: 12.75,
    inCart: false,
    count: 0,
    total: 0
};

